branches:
  only:
  - master
  - stable
  - dev

# Set build language to Python
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
- pip install poetry
install:
  - poetry install
script:
  - pytest --cov=./ --cov-report xml

# Report results to DeepSource
after_success:
  # Install deepsource CLI
  - curl https://deepsource.io/cli | sh

  # Report coverage artifact to 'test-coverage' analyzer
  - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
